# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Stat video

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: start statistical videos
      run: |
        cd Statistician
        python stat_video.py > ../meta-minesweeper/static/v.json
        python get_pb.py --json_dir ../meta-minesweeper/static/v.json > ../meta-minesweeper/static/pb.json
        python get_tournament.py --json_dir ../meta-minesweeper/static/v.json > ../meta-minesweeper/static/tournament.json
        cd ..
    - name: push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add meta-minesweeper/static/v.json meta-minesweeper/static/pb.json
        git commit -m "auto commit"
    - name: Pull changes
      run: git pull -r
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install and Build
      run: |
        cd meta-minesweeper
        npm install
        npm run build
        cd ..
        mkdir meta-minesweeper/dist/video/
        cp Arbiter_0.52.3/replays/*.avf meta-minesweeper/dist/video/
        cp Arbiter_0.52.3/replays2/*.avf meta-minesweeper/dist/video/
        mv meta-minesweeper/public/video_storage/flop meta-minesweeper/dist/flop
    - name: buildAndDeploy
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        branch: github-page
        folder: meta-minesweeper/dist


